language: go

go:
 - 1.13.x
 - 1.12.x
 - master
arch:
  - amd64
  - ppc64le
env:
 global:
  - GO111MODULE=on
  - GOFLAGS="-mod=readonly"

matrix:
  fast_finish: true
  allow_failures:
    - go: master

# Get deps, build, test, and ensure the code is gofmt'ed.
script:
 - go build -v ./...
 - go test -v ./...
 - diff <(gofmt -d .) <("")
